### ISSUE TITLE
{Web} Error when clicking on the pull requests button

### ISSUE THREAD

**Issue by codejamtc** [standlove/percy-issues#10]
![image](https://user-images.githubusercontent.com/42398485/51480121-e1d88580-1d55-11e9-8a11-dc6f24def6f3.png)

1. Open the web application
2. Select a branch and create some files and save as draft
3. Click Pull-request

**Actual:** Error when clicking on the pull requests button

**Expected:** Should not show an error

**Reproducibility Rate:** 3/3

**Environment:** Firefox 64.0.2 (64-bit), Microsoft Edge 42.17134.1.0 and Chrome 71.0.3578.98 (HP Pavilion x360 14 inch; Windows 10)

**Comment by liuliquan** [comment]
What's the error?

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/51534913-b95f9280-1e0c-11e9-8581-98454678f282.png)

**Comment by liuliquan** [comment]
This is weird, I've never seen something like this.

**Comment by liuliquan** [comment]
Do you have an ending "/" of repo url when login?

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/51539646-24639600-1e1a-11e9-8346-4b7004104f51.png)
 @liuliquan Yes

**Comment by liuliquan** [comment]
what's the url of the pull request shown in browser?

**Comment by codejamtc** [comment]
https://bitbucket.org/codejamtc/yaml-editor//pull-requests/new?source=PercyEditor&t=1#diff

**Comment by codejamtc** [comment]
I think we have to remove the ending / while login?

If I use https://bitbucket.org/codejamtc/yaml-editor/ while login - Issue happens
If I use https://bitbucket.org/codejamtc/yaml-editor while login - No issue

**Comment by liuliquan** [comment]
yes
