### ISSUE TITLE
{Electron} Application stuck at the Atlassian login page

### ISSUE THREAD

**Issue by codejamtc** [standlove/percy-issues#12]
![image](https://user-images.githubusercontent.com/42398485/51480369-7e028c80-1d56-11e9-8bde-c73b7c3b283e.png)

1. Open the web application
2. Select a branch and create some files and save as draft
3. Click Pull request
4. Fill the Atlassian credentials and login

**Actual:** Application stuck at the Atlassian login page

**Expected:** Login process should be completed and the popup should close without any issues

**Reproducibility Rate:** 3/3

**Environment:** (HP Pavilion x360 14 inch; Windows 10)

**Comment by liuliquan** [comment]
It's slow network

**Comment by liuliquan** [comment]
Now opens in system browser
