### ISSUE TITLE
{Electron}{Web} Can't add files if the user creates a new branch

### ISSUE THREAD

**Issue by codejamtc** [standlove/percy-issues#13]
![image](https://user-images.githubusercontent.com/42398485/51480570-fbc69800-1d56-11e9-850c-6b346f6b7d94.png)

1. Open the web application
2. Create a branch
3. Click Add file

**Actual:** Can't add files if the user creates a new branch

**Expected:** User should able to create an application first and then able to create a file

**Reproducibility Rate:** 3/3

**Environment:** Firefox 64.0.2 (64-bit), Microsoft Edge 42.17134.1.0 and Chrome 71.0.3578.98 (HP Pavilion x360 14 inch; Windows 10)

**Comment by liuliquan** [comment]
Client did not asks to create new application folder, this is enhancement

**Comment by standlove** [comment]
It's never requested by client ... so we won't fix this.
