### ISSUE TITLE
{Electron} Property creation window is not getting closed.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#18]
Steps to Reproduce

1. Login to electron app
2. create a new property
3. Property created window is not getting closed.

Actual Result

Property created window is not getting closed.

Expected Result

Property created window should get closed.

Frequency:

5/5

Device: Desktop
OS : Windows 7 32 bit

Images

![edit](https://user-images.githubusercontent.com/13567734/51484514-c86d2300-1dc1-11e9-90ba-180572894bef.jpg)

**Comment by liuliquan** [comment]
I can't reproduce it?

**Comment by standlove** [comment]
I think he means the edit property panel is changed to readonly property panel after submitting. 

It's desired actually.

**Comment by liuliquan** [comment]
That's desired behavior with intention.

**Comment by Jacob15** [comment]
@liuliquan No issues then.
