### ISSUE TITLE
error message should be adjusted when a large number is entered

### ISSUE THREAD

**Issue by winterflame** [standlove/percy-issues#2]
### Reproduction Steps ###

1. open the web app, fill with valid repo credentials, login

2. edit a property

3. change its value type to number and enter a long number for it

4. save it

### Expected Result ###

Error message should be adjusted when a large number is entered, e.g. "Max supported value is 100000000".

### Actual Result ###

*See screenshot, currently the error message indicates it is not a valid number.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *OS X EI Capitan Version 10.11.6*

**Comment by winterflame** [comment]
![2](https://user-images.githubusercontent.com/4590317/51476285-16812700-1dc0-11e9-96b4-c8dce337460e.png)

**Comment by standlove** [comment]
w
