### ISSUE TITLE
{Electron} Add environment is not reflected in the folder.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#20]
Steps to reproduce

1. Login to app.
2. Use open folder to open project.
3. Add a new file and name it.
4. Add a new environment file which is not there.
5. In the file which is added add environment.
6. Added environment ex.dev is not getting reflected in the config file.

Actual Result

Added environment is not getting reflected in the config file.

Expected Result

Added environment should reflect in the config file.

Frequency

5/5'

Device: Desktop
OS: Windows  7 32bit

Images/Video

http://www.screencast.com/t/lpwX61L7C

**Comment by standlove** [comment]
You need to reopen the file to reload the env.
