### ISSUE TITLE
{Web}Login failed message while login.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#21]
Steps to reproduce

1. Deploy the app.
2. Open using private window.
3. Login failed message.

Actual Result

Login failed message is getting appeared while login.

Expected Result

Login failed message should not appear.

Frequency

5/5'

Device: Desktop
OS: Windows  7 32bit
Browser: IE 11 latest

Images/Video

![loginfailed](https://user-images.githubusercontent.com/13567734/51486429-ab871e80-1dc6-11e9-997d-1cf303a39653.jpg)

**Comment by standlove** [comment]
I don't follow the steps ...
