### ISSUE TITLE
{Electron} Suggest to remove menu icons while login with atlassian account.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#22]
Steps to reproduce

1. Login to app.
2. Use open repo to open project.
3. Make some changes and commit.
4. Click on Pull request.
5. In the new window open observe the menu icons.

Actual Result

Menu icons is getting displayed in the new window.

Expected Result

Better to remove menu icons.

Frequency

5/5'

Device: Desktop
OS: Windows  7 32bit

Images/Video

![menuicons](https://user-images.githubusercontent.com/13567734/51487000-2866c800-1dc8-11e9-9e7b-ebed87c183e5.jpg)

**Comment by liuliquan** [comment]
Now opens in system browser
