### ISSUE TITLE
{Electron}Commit changes is not enable after deleting file in the dashboard.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#24]
Steps to reproduce

1. Login to app.
2. Use open repo to open project.
3. Delete a file in dashboard.
4. Commit changes is not getting enabled.

Actual Result

Commit changes is not getting enabled.

Expected Result

Commit changes should get enabled.

Frequency

5/5'

Device: Desktop
OS: Windows  7 32bit

Images/Video

http://www.screencast.com/t/kBoQQLNBn

**Comment by liuliquan** [comment]
Deleting file is immediately pushed to repo
