### ISSUE TITLE
{Electron}{Web} Conflicting line(s) is/are not highlighted 

### ISSUE THREAD

**Issue by codejamtc** [standlove/percy-issues#25]
![image](https://user-images.githubusercontent.com/42398485/51490003-887d5000-1d6f-11e9-8426-09fe15025d03.png)

1. Open the web application and login
2. Select a branch
3. Create a conflict
4. Click Merge master branch button

**Actual:** Conflicting line(s) is/are not highlighted 

**Expected:** Conflicting lines should be highlighted so that user can easily differentiate the lines to choose a file to resolve the conflict. If it is a large file use has to manually check the diff

**Reproducibility Rate:** 3/3

**Environment:** Firefox 64.0.2 (64-bit), Microsoft Edge 42.17134.1.0 and Chrome 71.0.3578.98 (HP Pavilion x360 14 inch; Windows 10)

**Comment by standlove** [comment]
hmm... not sure if we can use this: https://www.npmjs.com/package/diff

Or maybe it's too much for a webapp ...
