### ISSUE TITLE
inconsistent style for dropdown selected option

### ISSUE THREAD

**Issue by winterflame** [standlove/percy-issues#28]
### Reproduction Steps ###

1. open the web app, fill with valid repo credentials, login

2. click on the branch name, observe the style

3. click on the "Application" dropdown list, observe

### Expected Result ###

Should use same style for selected option - use checkmark or just highlight the option.

### Actual Result ###

*See screenshots.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14.2*

Browser: *Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)*

**Comment by winterflame** [comment]
![n](https://user-images.githubusercontent.com/4590317/51509097-f6d71680-1e32-11e9-98e8-3269920befed.jpg)

![y](https://user-images.githubusercontent.com/4590317/51509101-f6d71680-1e32-11e9-9c80-ae4ca4d60977.jpg)

**Comment by standlove** [comment]
won't fix
