### ISSUE TITLE
clicking outside of the modal should dismiss it

### ISSUE THREAD

**Issue by winterflame** [standlove/percy-issues#29]
### Reproduction Steps ###

1. open the web app, fill with valid repo credentials (on master branch), login

2. change both files in master branch and "newBranch" branch

3. click to merge master branch

4. click outside of the modal, observe

### Expected Result ###

Clicking outside of the modal should dismiss it, just like other modals (e.g. "Add New File" modal).

### Actual Result ###

*See screenshots.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14.2*

Browser: *Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)*

**Comment by winterflame** [comment]
![o](https://user-images.githubusercontent.com/4590317/51509405-e96e5c00-1e33-11e9-90c2-06ed54eeccfb.jpg)

**Comment by liuliquan** [comment]
It's with intention. The conflict modal is expensive than other modal (it loads file content),  and it's important. So shouldn't be accidentally dismissed by clicking outside. User has to explicitly click "CANCEL" button to dismiss it.

**Comment by winterflame** [comment]
Thanks for clarification.
