### ISSUE TITLE
"Action" column should be removed from the table (for master branch)

### ISSUE THREAD

**Issue by winterflame** [standlove/percy-issues#31]
### Reproduction Steps ###

1. open the web app, fill with valid repo credentials (on master branch), login

2. observe the table

### Expected Result ###

"Action" column should be removed from the table, since all "Delete" buttons are disabled, user could not do anything.

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14.2*

Browser: *Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)*

**Comment by winterflame** [comment]
![ac](https://user-images.githubusercontent.com/4590317/51510642-d7db8300-1e38-11e9-86f7-53e897391c8a.jpg)

**Comment by standlove** [comment]
won't fix
