### ISSUE TITLE
it does not select the source branch automatically when creating new merge request

### ISSUE THREAD

**Issue by winterflame** [standlove/percy-issues#32]
### Reproduction Steps ###

1. open the web app, fill with valid repo credentials (on master branch), login

2. create a new branch "branchNew", add some files, commit changes

3. then click "Pull Request", observe

### Expected Result ###

While opening the new page, it should select the source branch automatically for us (in this case it's "branchNew").

### Actual Result ###

*See screenshots, user has to select the source branch from the dropdown.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.14.2*

Browser: *Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)*

**Comment by winterflame** [comment]
![bn](https://user-images.githubusercontent.com/4590317/51511114-f3478d80-1e3a-11e9-8325-06b5085d965f.jpg)

**Comment by winterflame** [comment]
![sel](https://user-images.githubusercontent.com/4590317/51511185-2d189400-1e3b-11e9-865f-5f253edefb7f.jpg)

**Comment by liuliquan** [comment]
I'm not sure whether gitlab supports specify source branch
