### ISSUE TITLE
{Electron}{Web}Every time a new session/window appears while navigating to Atlassian.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#33]
Steps to Reproduce

1. Login to app
2. Open repo option open a repo.
3. Create Merge request for new branch
4. Click pull request. New window opens.
5. Click pull request again. New window opens.
 
Actual Result
New window is opening again and again.

Expected Result
Able to perform the same operation in the same window.

Frequency:

5/5

Device: Laptop
OS : Windows 7 32 bit

Images/Video
http://www.screencast.com/t/czq4JinW7ZqS

**Comment by liuliquan** [comment]
I want to change to open the link in system default browser, <del>but I'm afraid it's not possible to control it for same browser tab.</del>

Is there a way to control it in browser for same tab?

**Comment by standlove** [comment]
Just open it in the browser, why it should be opened in the same tab?

**Comment by standlove** [comment]
and I think it's duplicated with #12

**Comment by standlove** [comment]
you can close duplicated issues. @liuliquan
