### ISSUE TITLE
{Electron}{Web} Vertical scroll doesnt appear in the view details.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#37]
Steps to Reproduce

1. Login to web app/electron app.
2. Select Master branch.
3. click on a yaml file in dashboard.
4. View details.
5. Vertical scroll bar doesnt appear.

Actual Result

Vertical scroll bar doesn't appear.

Expected Result

Vertical Scroll bar should appear.

Frequency:

5/5

Device: Laptop
OS: Windows 7 32 bit

Images

![vertical](https://user-images.githubusercontent.com/13567734/51518788-0a8b7880-1e45-11e9-8b9a-bfe3c2fc830a.jpg)

**Comment by standlove** [comment]
it's because the yaml has no more content.
