### ISSUE TITLE
{Electron}{Web} Suggestion to rename tooltip as "Sync Master Branch"

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#42]
Steps to Reproduce

1. Login to webapp/electron.
2. Open the remote repo option open the repo.
3. Create a new branch and then Merge with Master branch.
4. Hover the tooltip over Merge Master branch.
5. Suggest to show it as "Sync with Master branch".

Actual Result

At present it shows "Merge with Master branch".

Expected Result

Merge with Master branch tooltip to be replaced with "Sync with Master branch".

Frequency:

5/5

Device: Laptop
OS : Windows 7 32 bit

Images

![merge](https://user-images.githubusercontent.com/13567734/51544233-77befe00-1e85-11e9-91c7-95e25655fc26.jpg)

**Comment by standlove** [comment]
no, merge is more standard.
