### ISSUE TITLE
{Electron}Suggest to have focus on current filename while scrolling left/right.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#43]
Steps to Reproduce

1. Login to electron app.
2. Select Open folder option and open a Project folder.
3. Open multiple files in the dashboard.
4. Scroll left/right.
5. While scrolling the focus is not in the current file.

Actual Result

Focus is not in the current file while scrolling left/right.

Expected Result

Focus should be in the current file.

Frequency:

5/5

Device: Laptop
OS: Windows 7 32 bit

Images/ Video

http://www.screencast.com/t/4Pe6zuusv

**Comment by standlove** [comment]
won't fix
