### ISSUE TITLE
{Electron} Space occupied by the new file is not getting cleared after deletion.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#44]
Steps to Reproduce

1. Login to electron app.
2. Select Open folder option and open a Project folder.
3. Open multiple files in the dashboard.
4. Add a new file again.
5. Close the untitled file.
6. Space created in the file bar is not getting removed.

Actual Result

Space created is not getting removed.

Expected Result

Space created should get removed.

Frequency:

5/5

Device: Laptop
OS: Windows 7 32 bit

Images/ Video

http://www.screencast.com/t/67mykMaI

**Comment by standlove** [comment]
won't fix
