### ISSUE TITLE
{Electron} Editing file externally results in disabling save,Reset buttons.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#45]
Steps to Reproduce

1. Login to electron app.
2. Select Open folder option and open a Project folder.
3. Edit a file through dashboard..
4. Save it. 
5. Edit file externally since it has some errors. After selecting OK to the alert, SAVE & RESET button is getting disabled.

Actual Result

SAVE & RESET button is getting disabled.

Expected Result

SAVE & RESET button should not get disabled till the user rectify the issue with file.

Frequency:

5/5

Device: Laptop
OS: Windows 7 32 bit

Images/ Video

http://www.screencast.com/t/5VxgEEoRp

**Comment by kinfkong** [comment]
It looks like we do not need to fix this.
Because after the file is reload, it has been "saved", not necessary to save again(and also cannot reset), so it is wrong to enable the buttons.

**Comment by standlove** [comment]
Ok thanks.
