### ISSUE TITLE
{Vscode} Adding Environment file result in creating environments file.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#46]
Steps to Reproduce

1. Login to vscode.
2. Open project folder.
3.. Right click and create a new environment file.
4. Environments file is created instead of Environment file.

Actual Result

Environments file is created instead of environment file.

Expected Result

Environment file should created.

Frequency:

5/5

Device: Laptop
OS: Windows 7 32 bit

Images/ Video

http://www.screencast.com/t/NAvsyPVr

**Comment by liuliquan** [comment]
It's expected.

"environments.yaml" is the default config, and it can be changed in extension config.
