### ISSUE TITLE
{Electron}Suggestion to make Apps name editable in text box while creating new file

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#49]
Steps to Reproduce:

1. Login to Electron app.
2. Use Open folder to open a project.
3. Click on the Elipses near apps and select add new file.
4. In the file name text box apps is not editable.( If a user wants to create a file in app1, app2 it is not possible here).

Actual Result

Apps name is not editable now.

Expected Result

Suggestion to make apps name editable.

Frequency:

5/5

Device: Desktop
OS : Windows 7 32bit

Images

![apps](https://user-images.githubusercontent.com/13567734/51677636-461e7200-2000-11e9-9374-7e1ccb334135.jpg)

**Comment by standlove** [comment]
won't fix
