### ISSUE TITLE
{Electron}{Webapp}Field values are getting cleared while logging with username(invalid)

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#51]
### Steps to Reproduce ###

1. Open webapp/Electron app.
2. Enter username with spaces in it.
3.  Enter Password.
4.  Give repo URL
5. Click Login.
6. Logout.
7. Observe the form fields having Username, Password, repo URL.( Blank )

### Actual Result ###

Form fields appearing blank while logging with username having spaces in it.

### Expected Result ###

Form fields should not get cleared.

### Frequency ###

5/5

### Device ###

Laptop

### OS ###

Windows 7 32 bit

### Browser ###

N/A -Electron
Chrome(Latest) -Webapp

### Images/Video ###

http://www.screencast.com/t/qM2sHegJe

**Comment by standlove** [comment]
cannot reproduce.
