### ISSUE TITLE
{Electron}{Webapp}Form fields edited error message is not getting cleared while using back button.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#52]
### Steps to Reproduce ###

1. Open Webapp, Electron app
2. Click on the Username field. Leave it blank
3. Click on the Password field. Leave it blank.
4. Click on the Repo URL field. Leave it blank.
5. Click Back button.
6.  Select Open repo now.
7. Observe Username, Password, Rep fields error message not cleared.

### Actual Result ###

Error message is not getting cleared while using Back  button.

### Expected Result ###

Error message should get cleared while using Back button.

### Frequency ###

5/5

### Device ###

Laptop

### OS ###

Windows 7 32 bit

### Browser ###

N/A

### Images/Video ###
http://www.screencast.com/t/lgOsizCIxlH

**Comment by standlove** [comment]
won't fix.
