### ISSUE TITLE
{Electron}{Webapp} Repository URL is not validating properly.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#57]
### Steps to Reproduce ###

1. Login to web app, electron app.
2. Enter username/Pwd, repo with gitlab.
3. Login. Observe
4. User able to enter for bitbucket instead gitlab.

### Actual Result ###

Repository URL is not validating properly.

### Expected Result ###

Repository URL should validate properly.

### Frequency ###

5/5

### Device ###

Laptop

### OS ###

Windows 7 32 bit

### Browser ###

Chrome(latest)

### Images/Video ###

http://www.screencast.com/t/ZKVu8qwtd10b

**Comment by standlove** [comment]
Can you just give screenshots ... ?

**Comment by Jacob15** [comment]
@standlove  Sure. Attached
![repo-1](https://user-images.githubusercontent.com/13567734/51760126-c1ab1c80-20ef-11e9-9ee7-53fd3f5e546c.jpg)
![repo-2](https://user-images.githubusercontent.com/13567734/51760139-ca035780-20ef-11e9-990e-177110b5fb96.jpg)

**Comment by standlove** [comment]
gitlab is fine ...
