### ISSUE TITLE
{Electron}{Webapp}Suggestion to show path till main repository name

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#58]
### Steps to Reproduce ###

1. Login to web app,electron app.
2. Enter username/Pwd, repo till branch name
3. Login.
4. Observe the text near the branch name. it shows till branch name . it should show only till repository name.

### Actual Result ###

Suggestion to show the text till repository name.

### Expected Result ###

Suggestion to show the text till repository name.

### Frequency ###

5/5

### Device ###

Laptop

### OS ###

Windows 7 32 bit

### Browser ###

Chrome(latest)

### Images/Video ###

http://www.screencast.com/t/efP0TPPh

**Comment by standlove** [comment]
The video in the link is broken ...  @Jacob15 

![image](https://user-images.githubusercontent.com/2214734/51757879-7c8ee680-20ff-11e9-8332-787b4e3febec.png)

**Comment by Jacob15** [comment]
@standlove Attached screenshot.
![repo-branch](https://user-images.githubusercontent.com/13567734/51760523-9b39b100-20f0-11e9-8786-f12ddc4909aa.jpg)

**Comment by standlove** [comment]
won't fix.
