### ISSUE TITLE
it will create same files for the new branch based on current branch while creating new branch

### ISSUE THREAD

**Issue by winterflame** [standlove/percy-issues#7]
### Reproduction Steps ###

1. open the web app, fill with valid repo credentials (suppose we're on master branch), login

2. click on the branch name

3. click "+Create Branch"

4. enter "developer", click CREATE, observe

### Expected Result ###

Should only create the new branch "developer", not clone the files from branch "master".

### Actual Result ###

*See screenshot.*

### Screenshots ###

*If not attached, please check comment section.*

### Issue Information ###

Device: *Mac Book Pro*

OS: *OS X EI Capitan Version 10.11.6*

Browser: *Latest Firefox*

**Comment by winterflame** [comment]
![4](https://user-images.githubusercontent.com/4590317/51477693-30246d80-1dc4-11e9-9dd9-924d5fadbbe6.png)

**Comment by liuliquan** [comment]
New branch is based on master, it was requirement from client.

**Comment by winterflame** [comment]
Closed, thx.
